#!/usr/bin/env python3
"""
Unit tests for image processing functions in stereo module.
Tests comparison between custom load+preprocess and dust3r load_images.
"""

import tempfile
from pathlib import Path

import cv2
import numpy as np
import pytest
import torch
from dust3r.utils.image import load_images as dust3r_load_images
from loguru import logger

from stereo.image import convert_image, load_image, preprocess_image

# Project root (pythonpath configured in pyproject.toml)
project_root = Path(__file__).resolve().parents[2]


def load_images_pair(image1_path, image2_path, size=None):
    """Load and preprocess image pair for MASt3R inference."""
    logger.debug(f"Loading images: {image1_path}, {image2_path}")
    assert size is not None, "Size must be provided"
    images = dust3r_load_images([image1_path, image2_path], size=size)
    return images


@pytest.fixture
def test_images():
    """Set up test fixtures."""
    # Use relative path from project root
    test_dir = project_root / "output" / "extracted_pairs" / "scene_3" / "0"
    image1_path = test_dir / "frame_1.png"
    image2_path = test_dir / "frame_2.png"
    size = 512

    # Skip test if test images don't exist (they may need to be generated first)
    if not image1_path.exists() or not image2_path.exists():
        pytest.skip(
            f"Test images not found. Expected at: {test_dir}\n"
            "These may need to be generated by running extract_pairs first."
        )

    return {"image1_path": image1_path, "image2_path": image2_path, "size": size}


def test_load_and_preprocess_vs_dust3r_load_images(test_images):
    """Test that load_image_new + preprocess_image_new produces same output as dust3r load_images."""

    # Method 1: Using our custom functions
    image1 = load_image(test_images["image1_path"], size=test_images["size"])
    image2 = load_image(test_images["image2_path"], size=test_images["size"])

    processed1 = preprocess_image(image1, size=test_images["size"], idx=0)
    processed2 = preprocess_image(image2, size=test_images["size"], idx=1)

    custom_result = [processed1, processed2]

    # Method 2: Using dust3r load_images
    dust3r_result = dust3r_load_images(
        [test_images["image1_path"], test_images["image2_path"]],
        size=test_images["size"],
    )

    # Compare results
    assert len(custom_result) == len(dust3r_result), (
        "Number of processed images should match"
    )

    for i, (custom_img, dust3r_img) in enumerate(
        zip(custom_result, dust3r_result, strict=True)
    ):
        # Compare tensor shapes
        assert custom_img["img"].shape == dust3r_img["img"].shape, (
            f"Image {i} tensor shapes should match"
        )

        # Compare true_shape
        np.testing.assert_array_equal(
            custom_img["true_shape"],
            dust3r_img["true_shape"],
            f"Image {i} true_shape should match",
        )

        # Compare idx
        assert custom_img["idx"] == dust3r_img["idx"], f"Image {i} idx should match"

        # Compare instance
        assert custom_img["instance"] == dust3r_img["instance"], (
            f"Image {i} instance should match"
        )

        # Compare tensor values (with some tolerance for floating point differences)
        torch.testing.assert_close(
            custom_img["img"],
            dust3r_img["img"],
            rtol=1e-5,
            atol=1e-6,
            msg=f"Image {i} tensor values should be close",
        )


def test_load_images_pair_vs_dust3r_load_images(test_images):
    """Test that load_images_pair produces same output as dust3r load_images."""

    # Method 1: Using our load_images_pair function
    custom_result = load_images_pair(
        test_images["image1_path"], test_images["image2_path"], size=test_images["size"]
    )

    # Method 2: Using dust3r load_images
    dust3r_result = dust3r_load_images(
        [test_images["image1_path"], test_images["image2_path"]],
        size=test_images["size"],
    )

    # Compare results
    assert len(custom_result) == len(dust3r_result), (
        "Number of processed images should match"
    )

    for i, (custom_img, dust3r_img) in enumerate(
        zip(custom_result, dust3r_result, strict=True)
    ):
        # Compare tensor shapes
        assert custom_img["img"].shape == dust3r_img["img"].shape, (
            f"Image {i} tensor shapes should match"
        )

        # Compare true_shape
        np.testing.assert_array_equal(
            custom_img["true_shape"],
            dust3r_img["true_shape"],
            f"Image {i} true_shape should match",
        )

        # Compare idx
        assert custom_img["idx"] == dust3r_img["idx"], f"Image {i} idx should match"

        # Compare instance
        assert custom_img["instance"] == dust3r_img["instance"], (
            f"Image {i} instance should match"
        )

        # Compare tensor values (with some tolerance for floating point differences)
        torch.testing.assert_close(
            custom_img["img"],
            dust3r_img["img"],
            rtol=1e-5,
            atol=1e-6,
            msg=f"Image {i} tensor values should be close",
        )


@pytest.mark.parametrize("size", [224, 512, 1024])
def test_different_sizes(test_images, size):
    """Test with different size parameters."""
    # Test load_images_pair vs dust3r
    custom_result = load_images_pair(
        test_images["image1_path"], test_images["image2_path"], size=size
    )
    dust3r_result = dust3r_load_images(
        [test_images["image1_path"], test_images["image2_path"]], size=size
    )

    # Compare tensor shapes
    for i, (custom_img, dust3r_img) in enumerate(
        zip(custom_result, dust3r_result, strict=True)
    ):
        assert custom_img["img"].shape == dust3r_img["img"].shape, (
            f"Size {size}, Image {i} tensor shapes should match"
        )

        # Compare tensor values
        torch.testing.assert_close(
            custom_img["img"],
            dust3r_img["img"],
            rtol=1e-5,
            atol=1e-6,
            msg=f"Size {size}, Image {i} tensor values should be close",
        )


def test_video_frame_reading_vs_save_and_load():
    """Test that direct video frame reading is equivalent to cv2.imwrite + load_image."""
    # Use a video file from the assets (relative path from project root)
    video_path = (
        project_root
        / "assets"
        / "reconstruction"
        / "scene_3"
        / "camera_1"
        / "camera_1.mp4"
    )

    # Skip test if video file doesn't exist
    if not video_path.exists():
        pytest.skip(f"Test video not found: {video_path}")

    # Import VideoReader from the video module
    from video import VideoReader

    # Create a temporary directory for saving the frame
    with tempfile.TemporaryDirectory() as temp_dir:
        temp_dir_path = Path(temp_dir)
        # Method 1: Direct frame reading from video
        video_reader = VideoReader.open_video_file(str(video_path))
        ret, direct_frame = video_reader.read(frame_number=0)  # Read first frame
        video_reader.release()

        assert ret, "Failed to read frame from video"
        assert direct_frame is not None, "Direct frame is None"

        # Method 2: Save frame with cv2.imwrite and load with load_image
        temp_image_path = temp_dir_path / "temp_frame.png"
        cv2.imwrite(str(temp_image_path), direct_frame)

        # Load the saved image using load_image function
        loaded_image = load_image(str(temp_image_path), size=512)

        # Convert direct frame to PIL Image for comparison
        direct_pil = convert_image(direct_frame)

        # Compare the images
        # Both should be PIL Images in RGB format
        assert loaded_image.mode == direct_pil.mode, "Image modes should match"
        assert loaded_image.size == direct_pil.size, "Image sizes should match"

        # Convert to numpy arrays for pixel comparison
        loaded_array = np.array(loaded_image)
        direct_array = np.array(direct_pil)

        # Compare pixel values (should be identical)
        np.testing.assert_array_equal(
            loaded_array,
            direct_array,
            "Pixel values should be identical between direct reading and save+load",
        )

        print("✅ Video frame reading test passed:")
        print(f"   - Direct frame shape: {direct_frame.shape}")
        print(f"   - Loaded image size: {loaded_image.size}")
        print(f"   - Image mode: {loaded_image.mode}")
